name: Deploy Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Cache npm dependencies
        uses: ./.github/actions/cache

      - name: Install dependencies
        run: npm install

      - name: Build docs
        run: npm run docs:build

    #   - name: Deploy docs
    #     run: |
    #       npm run docs:deploy

    #   - name: Upload docs
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: docs
    #       path: docs/.vitepress/dist
    #       retention-days: 30