name: Pack Package

on:
  workflow_dispatch:

  pull_request:
    types:
      - closed
    branches:
      - development
      
  repository_dispatch:
    types: [pr-merged-to-main]

permissions:
  id-token: write
  contents: read

jobs:
  pack-package:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true || (github.event_name == 'repository_dispatch' && github.event.action == 'pr-merged-to-main') || ${{ !(github.event.pull_request.base.ref == 'development' && github.event.pull_request.head.ref == 'bump-version-branch') }}
    name: Pack Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node

      - name: Cache npm dependencies
        uses: ./.github/actions/cache

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build:package

      - name: Pack package
        run: npm pack

      - name: List files
        run: ls -la

      - name: Copy path of packed package
        id: packed_package_path
        run: |
          echo "PACKED_PACKAGE_PATH=$(find . -maxdepth 1 -type f -name 'llm-exe-*.tgz')" >> $GITHUB_ENV

      - name: Upload packed package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ env.PACKED_PACKAGE_PATH }}
          retention-days: 30
