name: Pack Package

on:
  workflow_dispatch:

  pull_request:
    types:
      - closed
    branches:
      - main
      - development

permissions:
  id-token: write
  contents: read

jobs:
  pack-package:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    name: Pack Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node

      - name: Cache npm dependencies
        uses: ./.github/actions/cache

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build:package

      - name: Pack package
        run: npm pack

      - name: Upload packed package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: "$(find . -maxdepth 1 -type f -name 'llm-exe-*.tgz')"
          retention-days: 30
