name: Test Package

on:
  workflow_dispatch:

  repository_dispatch:
    types: [pr-merged-to-main]

permissions:
  id-token: write
  contents: write

jobs:
  test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker container with Ollama & Node.js
        run: |
          docker build --build-arg OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }} -t my-ollama-env -f .github/Dockerfile .

      - name: Run tests inside the container
        run: |
          docker run --rm --entrypoint /bin/bash my-ollama-env -c "
            ollama serve & sleep 3;
            for model in 'deepseek-r1' 'llama3.1'; do
              echo Pulling model: \$model;
              ollama pull \$model || echo Skipping unavailable model: \$model;
            done;
            npm run test-examples
          "
