name: Test Package

on:
  workflow_dispatch:

  repository_dispatch:
    types: [pr-merged-to-main]

permissions:
  id-token: write
  contents: write

jobs:
  ollama_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ollama
        run: |
          docker run -d --name ollama -p 11434:11434 ollama/ollama:latest

      - name: Pull a model (e.g., Mistral)
        run: |
          curl -X POST http://localhost:11434/api/pull -d '{"name": "mistral"}'

      - name: Run inference
        run: |
          curl -X POST http://localhost:11434/api/generate -d '{"model": "mistral", "prompt": "Hello, world!"}'