name: Test Package

on:
  workflow_dispatch:
  workflow_run:
    workflows: "Run Tests"
    types: [completed]
  # repository_dispatch:
  #   types: [pr-merged-to-main]

permissions:
  id-token: write
  contents: write

jobs:
  test-package:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'development' && github.event.workflow_run.triggering_actor.login == 'devfrankduah') || (github.event_name == 'workflow_dispatch' && github.event.sender.login == 'devfrankduah') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Latest Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Cache npm dependencies
        uses: ./.github/actions/cache

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build:package

      - name: Pack package
        run: npm pack

      - name: List files
        run: ls -la

      - name: Copy path of packed package
        id: packed_package_path
        run: |
          echo "PACKED_PACKAGE_PATH=$(find . -maxdepth 1 -type f -name 'llm-exe-*.tgz')" >> $GITHUB_ENV

      # - name: Install dependencies in examples directory
      #   run: |
      #     jq --arg pkg "${{ env.PACKED_PACKAGE_PATH }}" '.dependencies["llm-exe"] = "file:" + $pkg' examples/package.json > examples/package.json.tmp && \
      #     mv examples/package.json.tmp examples/package.json && \
      #     cd examples && npm install

      - name: Run tests
        run: npm run test-examples

